serverAddr = "skyvaultnest.i234.me"
serverPort = 7000
auth.method = "token"
auth.token = "gugu1127"

[[proxies]]
name = "remote-desktop"
type = "tcp"
localIP = "192.168.0.103"
localPort = 3389
remotePort = 10000