[common]                                                                         
bind_port = 7000                                                                 
token = oreofrp                                                                  
dashboard_port = 7500                                                            
dashboard_user = oreo                                                            
dashboard_pwd = max0605124 